package project.hms.panels;

import java.awt.Color;
import project.hms.services.PatientRecordService;
import project.hms.services.StaffRecordService;
import project.hms.services.BookingService;
import project.hms.models.PatientData;
import project.hms.models.StaffData;
import project.hms.models.BookingData;

public class SchedulePanel extends javax.swing.JPanel {
    
    private final PatientRecordService patientRecordService = new PatientRecordService();
    private final StaffRecordService staffRecordService = new StaffRecordService();
    private final BookingService bookingService = new BookingService();
    
    public SchedulePanel() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0.2f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        creationDateLabel = new javax.swing.JLabel();
        patientInfoLabel = new javax.swing.JLabel();
        staffInfoLabel = new javax.swing.JLabel();
        appointmentLabel = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        bookIdField = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Staff:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Created:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Appointed at:");

        creationDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        creationDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        creationDateLabel.setText("date");

        patientInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientInfoLabel.setText("patient");

        staffInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        staffInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        staffInfoLabel.setText("staff");

        appointmentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        appointmentLabel.setForeground(new java.awt.Color(255, 255, 255));
        appointmentLabel.setText("datetime");

        searchBTN.setBackground(new java.awt.Color(102, 102, 102));
        searchBTN.setForeground(new java.awt.Color(255, 255, 255));
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        bookIdField.setBackground(new java.awt.Color(102, 102, 102));
        bookIdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookIdField.setForeground(new java.awt.Color(255, 255, 255));
        bookIdField.setText("Booking ID");
        bookIdField.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBTN)
                    .addComponent(appointmentLabel)
                    .addComponent(staffInfoLabel)
                    .addComponent(patientInfoLabel)
                    .addComponent(creationDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(creationDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientInfoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(staffInfoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(appointmentLabel))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        searchSched(Integer.parseInt(bookIdField.getText()));
    }//GEN-LAST:event_searchBTNActionPerformed

    public void searchSched(int searchBookID){
        BookingData bookingData = bookingService.searchSched(searchBookID);
        int patientId = bookingData.getPatientID();
        int staffId = bookingData.getStaffID();
        
        PatientData patientData = patientRecordService.searchPatientRecord(patientId);
        StaffData staffData = staffRecordService.searchStaffRecord(staffId);
        String patientName = patientData.getName();
        String staffName = staffData.getName();
        String staffPosition = staffData.getPosition();
        String date = String.valueOf(bookingData.getAppointmentDate());
        String time = String.valueOf(bookingData.getAppointmentTime());
        String dateTime = date + " | " + time;
        patientInfoLabel.setText("ID: " + patientId + " | Name: " + patientName);
        staffInfoLabel.setText("ID: " + staffId + " | Name: " + staffName + " | Position: " + staffPosition );
        appointmentLabel.setText(dateTime);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointmentLabel;
    private javax.swing.JTextField bookIdField;
    private javax.swing.JLabel creationDateLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel patientInfoLabel;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel staffInfoLabel;
    // End of variables declaration//GEN-END:variables
}
