package project.hms.panels;

import java.awt.Color;
import java.awt.Dimension;
import java.time.format.DateTimeFormatter;
import project.hms.services.PatientRecordService;
import project.hms.services.StaffRecordService;
import project.hms.services.BookingService;
import project.hms.models.PatientData;
import project.hms.models.StaffData;
import project.hms.models.BookingData;

public class SchedulePanel extends javax.swing.JPanel {
    
    private final PatientRecordService patientRecordService = new PatientRecordService();
    private final StaffRecordService staffRecordService = new StaffRecordService();
    private final BookingService bookingService = new BookingService();
    
    public SchedulePanel() {
        initComponents();
        setPreferredSize(new Dimension(900, 650));
        setBackground(new Color(0, 0, 0, 0.2f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        bookIdField = new javax.swing.JTextField();
        patientInfoField = new javax.swing.JTextField();
        creationField = new javax.swing.JTextField();
        staffInfoField = new javax.swing.JTextField();
        appointmentField = new javax.swing.JTextField();
        statusField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        deleteDelete = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        staffInfoField1 = new javax.swing.JTextField();
        patientInfoField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        creationField1 = new javax.swing.JTextField();
        appointmentField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        staffInfoField2 = new javax.swing.JTextField();
        bookingTablePanel1 = new project.hms.panels.BookingTablePanel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Staff");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Created at");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Appointed at:");

        searchBTN.setBackground(new java.awt.Color(102, 102, 102));
        searchBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBTN.setForeground(new java.awt.Color(255, 255, 255));
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        bookIdField.setBackground(new java.awt.Color(102, 102, 102));
        bookIdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookIdField.setForeground(new java.awt.Color(255, 255, 255));
        bookIdField.setToolTipText("Booking ID:");
        bookIdField.setCaretColor(new java.awt.Color(255, 255, 255));
        bookIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookIdFieldFocusGained(evt);
            }
        });
        bookIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdFieldActionPerformed(evt);
            }
        });

        patientInfoField.setBackground(new java.awt.Color(102, 102, 102));
        patientInfoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        patientInfoField.setForeground(new java.awt.Color(255, 255, 255));
        patientInfoField.setToolTipText("Booking ID:");
        patientInfoField.setCaretColor(new java.awt.Color(255, 255, 255));

        creationField.setBackground(new java.awt.Color(102, 102, 102));
        creationField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creationField.setForeground(new java.awt.Color(255, 255, 255));
        creationField.setToolTipText("Booking ID:");
        creationField.setCaretColor(new java.awt.Color(255, 255, 255));

        staffInfoField.setBackground(new java.awt.Color(102, 102, 102));
        staffInfoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staffInfoField.setForeground(new java.awt.Color(255, 255, 255));
        staffInfoField.setToolTipText("Booking ID:");
        staffInfoField.setCaretColor(new java.awt.Color(255, 255, 255));

        appointmentField.setBackground(new java.awt.Color(102, 102, 102));
        appointmentField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        appointmentField.setForeground(new java.awt.Color(255, 255, 255));
        appointmentField.setToolTipText("Booking ID:");
        appointmentField.setCaretColor(new java.awt.Color(255, 255, 255));

        statusField.setBackground(new java.awt.Color(102, 102, 102));
        statusField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusField.setForeground(new java.awt.Color(255, 255, 255));
        statusField.setToolTipText("Booking ID:");
        statusField.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status:");

        editBTN.setBackground(new java.awt.Color(102, 102, 102));
        editBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBTN.setForeground(new java.awt.Color(255, 255, 255));
        editBTN.setText("Update");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter ID:");

        deleteDelete.setBackground(new java.awt.Color(102, 102, 102));
        deleteDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteDelete.setForeground(new java.awt.Color(255, 255, 255));
        deleteDelete.setText("Delete");
        deleteDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDeleteActionPerformed(evt);
            }
        });

        clearBTN.setBackground(new java.awt.Color(102, 102, 102));
        clearBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBTN.setForeground(new java.awt.Color(255, 255, 255));
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");

        staffInfoField1.setBackground(new java.awt.Color(102, 102, 102));
        staffInfoField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staffInfoField1.setForeground(new java.awt.Color(255, 255, 255));
        staffInfoField1.setToolTipText("Booking ID:");
        staffInfoField1.setCaretColor(new java.awt.Color(255, 255, 255));

        patientInfoField1.setBackground(new java.awt.Color(102, 102, 102));
        patientInfoField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        patientInfoField1.setForeground(new java.awt.Color(255, 255, 255));
        patientInfoField1.setToolTipText("Booking ID:");
        patientInfoField1.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Time:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Time:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date:");

        creationField1.setBackground(new java.awt.Color(102, 102, 102));
        creationField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creationField1.setForeground(new java.awt.Color(255, 255, 255));
        creationField1.setToolTipText("Booking ID:");
        creationField1.setCaretColor(new java.awt.Color(255, 255, 255));

        appointmentField1.setBackground(new java.awt.Color(102, 102, 102));
        appointmentField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        appointmentField1.setForeground(new java.awt.Color(255, 255, 255));
        appointmentField1.setToolTipText("Booking ID:");
        appointmentField1.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Position:");

        staffInfoField2.setBackground(new java.awt.Color(102, 102, 102));
        staffInfoField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staffInfoField2.setForeground(new java.awt.Color(255, 255, 255));
        staffInfoField2.setToolTipText("Booking ID:");
        staffInfoField2.setCaretColor(new java.awt.Color(255, 255, 255));

        bookingTablePanel1.setBackground(new java.awt.Color(40, 40, 40));
        bookingTablePanel1.setForeground(new java.awt.Color(50, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteDelete))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(90, 90, 90))
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(staffInfoField)
                                .addComponent(staffInfoField1)
                                .addComponent(patientInfoField)
                                .addComponent(patientInfoField1)
                                .addComponent(staffInfoField2)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(creationField1)
                                .addComponent(creationField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGap(79, 79, 79)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(appointmentField1)
                                .addComponent(appointmentField)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(91, 91, 91)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 44, Short.MAX_VALUE)
                                    .addComponent(clearBTN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editBTN))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookingTablePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(staffInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffInfoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffInfoField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(deleteDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(creationField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(creationField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(appointmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(appointmentField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(patientInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(patientInfoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookingTablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        searchSched(Integer.parseInt(bookIdField.getText()));
    }//GEN-LAST:event_searchBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        editSched();
    }//GEN-LAST:event_editBTNActionPerformed

    private void bookIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIdFieldFocusGained
        bookIdField.setText("");
    }//GEN-LAST:event_bookIdFieldFocusGained

    private void deleteDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDeleteActionPerformed
        handleDelete();
        clearField();
    }//GEN-LAST:event_deleteDeleteActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        clearField();
    }//GEN-LAST:event_clearBTNActionPerformed

    private void bookIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdFieldActionPerformed
        searchSched(Integer.parseInt(bookIdField.getText()));
    }//GEN-LAST:event_bookIdFieldActionPerformed

    private void editSched(){
        int searchBookID = Integer.parseInt(bookIdField.getText().trim());
        String status = statusField.getText().trim();
        bookingService.editSchedule(searchBookID, status);
        clearField();
        statusField.setText("Book ID #" + String.valueOf(searchBookID) + " status updated: " + status);
    }
    
    private void searchSched(int searchBookID){
        BookingData bookingData = bookingService.searchSched(searchBookID);
        int patientId = bookingData.getPatientID();
        int staffId = bookingData.getStaffID();
        
        PatientData patientData = patientRecordService.searchPatientRecord(patientId);
        StaffData staffData = staffRecordService.searchStaffRecord(staffId);
        String patientName = patientData.getName();
        String staffName = staffData.getName();
        String staffPosition = staffData.getPosition();
        String status = bookingData.getStatus();
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MM:dd:yyyy");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("hh a");

        String creationDate = bookingData.getCreationDate().format(dateFormatter);
        String creationTime = bookingData.getCreationTime().format(timeFormatter);
        String appointmentDate = bookingData.getAppointmentDate().format(dateFormatter);
        String appointmentTime = bookingData.getAppointmentTime().format(timeFormatter);
        
        creationField.setText(creationDate);
        creationField1.setText(creationTime);
        appointmentField.setText(appointmentDate);
        appointmentField1.setText(appointmentTime);
        patientInfoField.setText(String.valueOf(patientId));
        patientInfoField1.setText(patientName);
        staffInfoField.setText(String.valueOf(staffId));
        staffInfoField1.setText(staffName);
        staffInfoField2.setText(staffPosition);
        statusField.setText(status);
    }
    
    private void handleDelete(){
        int bookId = Integer.parseInt(bookIdField.getText().trim());
        patientRecordService.deletePatientData(bookId);
        bookIdField.setText("Schedule Deleted!");
    }
    
    private void clearField(){
        bookIdField.setText("");
        appointmentField.setText("");
        appointmentField1.setText("");
        creationField.setText("");
        creationField1.setText("");
        patientInfoField.setText("");
        patientInfoField1.setText("");
        staffInfoField.setText("");
        staffInfoField1.setText("");
        staffInfoField2.setText("");
        statusField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appointmentField;
    private javax.swing.JTextField appointmentField1;
    private javax.swing.JTextField bookIdField;
    private project.hms.panels.BookingTablePanel bookingTablePanel1;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTextField creationField;
    private javax.swing.JTextField creationField1;
    private javax.swing.JButton deleteDelete;
    private javax.swing.JButton editBTN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField patientInfoField;
    private javax.swing.JTextField patientInfoField1;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField staffInfoField;
    private javax.swing.JTextField staffInfoField1;
    private javax.swing.JTextField staffInfoField2;
    private javax.swing.JTextField statusField;
    // End of variables declaration//GEN-END:variables
}
